name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2d0d57333e3982981801928ff71403a2d5b9beab6727be51aa1c413bbbbd19c"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
