name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4639746b31c6f2a1c743e9a12c7e573bba6858f1d34edc2763ac8333c70a11c"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
