name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0022e7c425a9ec5e992aff7770063af212d0cd7c24b519afd1e29a0c180c0b16"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
