name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "846cb600b965275f0b129c3c6ba239f7214ee7de86adfbd1a110516924f95225"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
