name = "Arcrepitus"
author = "AIGO Team"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dc448b15175b3f2ba4d6e8057f3eb2f4ba49fbad2ce3cdc421994811fcebcc0"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
