name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bf97dac8cb7564b7d984ebd5c34694041f3ffdbe5c7c9dd04db61a7583df083"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
