name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5637ded2bb2ed0daaf5e689e74d1a83c861723c52729a78b40a36d988792e9ce"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
