name = "Arcrepitus"
author = "AIGO Team"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb099c020496325e6bfc97b4201d2c7f65e4320becc984b63054ebbe803c3dc9"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
