name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f3110565922bd64277842f2989e43822244db59c9978d56cf04ff9d3f725ec"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
