name = "Arcrepitus"
author = "AIGO Team"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bc7615c25d05f544929aabfdc9a9a991d13adb8ed63f7c4bda7c04e006524da"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
