name = "Arcrepitus"
author = "AIGO Team"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "564d35fbd661cfbecb9b9f7852ab7e54f0b4ce3533cc8783a8b5ff34e771a1f0"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
