name = "Arcrepitus"
author = "AIGO Team"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13218fd60a951051015869d68309af0c7b8f983de449ef63d018858c570f0ece"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"
